name: KODAMA
channels:
  - defaults
dependencies:
  - bzip2
  - ca-certificates
  - expat
  - libexpat
  - libffi
  - libzlib
  - openssl
  - packaging
  - pip
  - python=3.11
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
      - opencv-python
      - opencv-python-headless