path: data
train: images/train
val: images/val

names:
  0: crosswalk
  1: opening-door
  2: opening-gate
  3: pedestrian
  4: rider
  5: animal
  6: stairs
  7: obstacle
  8: vehicle
  9: traffic sign
  10: traffic light
  11: pole
  12: bus stop
  13: bike rack
  14: tree
