split:
  seed: 42
  train_portion: 0.85
  train_sessions:
  - -5OCPnbrwJdu3jH70ieU7pUiFsOJQoeG
  - -PqSDmiEe2pXjmYHgxh4YEBsj0T5LU10
  - -koZLfrjI5P5NIBgB4f_4jpMSMxsd9pH
  - 1H3E6EdKXElNb9dwktawcA-tEBYUbu7J
  - 1rL8RTbI4jPqRkavZxrQbbM26iRfSLAH
  - 1sftEbnzzIfYBdODrjDO9TbhcnsyKjAv
  - 28tdwxgz-zPU06lpeDY3OPWTFxZyBv2c
  - 2N3D8fo4jJ7GsPFuC89q0QeXO1dEteWS
  - 2iQ4jyIxwXUInJKDYmBuoDltgad_GKC5
  - 3ok1zz3n49UtV6i2AGMLv-2gBifNtc56
  - 3sP_fftGJ6fKE8F-lShNvbgYh5tTcBJd
  - 4P1L1itAREhCiu6ZwFWRmOD5iCUdjcF3
  - 4Py0fr78AEVfKZAVmaspA7pO36WjMLUl
  - 53_TnXrp7ttT3xUyMSps6JSXdidyKw6o
  - 5ds11qbJuU0H6GEVLo67pCSNmTbpTsrL
  - 5wiNc10ZAN5qnULkU6whKbRb8OGFLxUl
  - 5z7n1PIsHGyQmO64hAlMynF3Cdj0rBeu
  - 66XHCmocuru678D4ehkbnBD9yjBpbOir
  - 6Zngp12ETEAAZnfliZdHRFJBJQU9V3ZU
  - 6uEJtqNVqHJA1tjeemumA-trgb9xnvt0
  - 75G7mMDsi4csa74ehbypzxLfs3ZJshsX
  - 7X41_wkj6FHIcIpxSuh4tRR6R8P_SAGr
  - 7YTgDkbGXoblYLN1IHcUMGFO2Sa5lyo_
  - 8GbY4HVFE794yBRg8-wMqeDi_uLHjQPX
  - 8WF0e5NO8I-90SR6uyKZvuB0gz59GUM0
  - 8bWymqLVx34nEZhZek77q8WqIEvRucxE
  - 8gGeL1XFBrc1UxxtyROYgtRGgzNRaVyY
  - 9e6t9GD8EEnQwpm-zYcFc8OjImoK2D7N
  - 9m1-lqCg93cYYGzfpXv-n-lQCpu1_yTs
  - 9zhwm8-HDoUub3dkVEp398Xdw9HYTC9m
  - ALYuoq-pWdqtJ-Jm9R8ceVzhsXYawzfi
  - AMWsWL1lxlW0NelUU8w8yL4psb1R1vCd
  - AUTqqeGB74PPSAJ6waiz6prT8DEVf-A7
  - AdtGuq73TlhK5miUkWcUO9BoKdnmV-8j
  - BNzLYFSMk1kYQFqnw8pD0w9_pf0g_4m7
  - ChcneDEXiD6dzznmQNtTnlVflFy2nK2s
  - D2fmg-h01L9EjZl89mFRyBOa1DhLY6hi
  - DD9W-6F3D126azdsR_Usvu6zkNqkP8XG
  - DSZAhX1NcHwzhDAPV0udk99FeuFdAqzu
  - DkGRMzPhvAIhmy0QHp_mko4dsRxEK5VY
  - DuPv9dnGn0U8eUTL3dRSJ0Rh25jMwg7u
  - EXUy7eoDpVbKR-bpIg-faiepUfqZwJ2v
  - FeJgoz6tfxhlDqiesDGIZdbM3VoE_HMZ
  - Fhw5qR8o7DO-EAhsnlqxc-y1zp0Y357Y
  - GC0nALNWkxktP4oXzRvOLm1lFkt_hlii
  - GEwWDMMe8FFo-wHxZ4Pg1chw15P2nEEz
  - HEmFiCyijsIoIt_sehLfZ4xyCUq06mss
  - IR6g8_ch0elPSFs9lLvSTGrfhJsB8tVU
  - J4PblHagnYNO09IdrDjQShle2Z0Dk-Yu
  - JrFB7oRxppNref18SJEl_t72ADmhGWlo
  - JtMYI6rJ4wiDsEVffAkee0kR5Zmrf8vM
  - KDo1FZFB0pRnxh8_sg3XDx5gpp9rqIQk
  - KIERO-z0fyfp_OsxbvxuSWkeAC2p-hXM
  - KMB_G-uuKE8-SNDAbRGQSzpEBpVGdsJI
  - LRWTaGC62fB3NflMQaOPXf0HJR1m5Ypp
  - LpjeyfDdXRDw03hbRDdm4e6MPcR0Ypua
  - M-VNejgLYhI2MxSNlyoU_0eZLXrFJE8G
  - MfB7TYQ85PEmYcoxFWusr5Qg3IyxID0f
  - MtwZFFClj_Si11UTnHXXgN4CjqmPulP2
  - MyiD6J_lPqZu6Gfeys5QLGWtnJIMe4fj
  - N2vCz9-hYT6sPeKYqKXC6LBNNEIiUuDy
  - NEljbgsZaaSaMyQwCHvre5n0RnVexfzE
  - P1mw_jQi2THNgjGtDW_jskg210PvjupW
  - QNYa4qqhEF7nmCX5rqY8cZXE4h1oGZtv
  - R0zL2no8ujqRzo45_vBv-ca8HSh_6vxo
  - RqOwmltcpedYcPhPygoVqCihidZ5LAiF
  - S7U2VKRn0NwTuhp1Qk67R7l8k5iYZFI-
  - SK1d5RB_ktBZhLvPs9-Q9hXeHojD49u-
  - SPoj3wSxZDDu1zDcE8RYTRxtxrRP_AMK
  - SRHpBZXk_0pKjk6SK23VOhoLZGZfnKFF
  - TTj3piLyS3X2V1Ce4fIgdKvhBCtIQOjc
  - U6btYjl9GEMJ0o5YEeLnayEvTYa8Yk-f
  - UGNwBEZMxhzlzXVyl8XUfflcvjGwdpA5
  - US7wvt5osva1gBg_TBJCKRwjXVFpM4dp
  - V3CUuaYiTdyEl-qcIa4OJdLlFwggCKGu
  - VDtaHRgxth3Kx3S1IQOv8snwcP2m2_Rh
  - VjpjnvAcYfG88ud095O2fv9dFUj4OAOM
  - W1ZpmAq74J8xfKg23BcwLx0QHfxM6W_w
  - WguegvD3gOx4PuRfGAxoDSOo2wlKjeU4
  - XOjHrx-neyD2GJuPsd5mgT9vNvytEzyL
  - XfXSSNa6hTGhdVyzsC9KepdxjY91vIzy
  - Xoe7Kec_tA-bzqYd6hDEMMF6-rFrZx1b
  - Y1bfx3vT3ky1BNxc2AjRe9Md2jbdvb6N
  - ZmFj3Y8i_Ydr-jF4yKDstmpgMdpBtc4H
  - Zodf1mn3rR80jtAik_zwIDgumTbfmbhm
  - _Syk0BTVCWUxQSKa-dSkzl0FBLj7a0RQ
  - _UTPXBuzIizvDtKewwJIiK77VZU-h_cg
  - a7bGB6aD6bcUMhl86R9HNNHUVUUxlS2c
  - aS0hVe_uSBiAMtWO1Dqc6zvMZt32j5JH
  - bDgP7lEiWvw6KcIimx8_iyWYtTHg3FON
  - bSo4owzNL_YnfHEb8OdzM8qT8UHOd8BQ
  - bYAxqF9cHadDvQVpTVb2ShohXapW09g-
  - bfTbc0atVxbLbnI5MHT3RqWVCj-4u8gp
  - c4Mh8piOiKI4EEHHQOLTbFUfCDLlq29P
  - cRWR9l7md-88131kPyM_8mfBQ93-0xhy
  - d3CKbaNbOPz-ZjLPUd6qD6wSNC3OKQxL
  - dB-D3W80IShuv4pBtc4EPn8JqAVpmQoE
  - dvUgguwseONxFnyefZ0q5qX8EEDNcoo-
  - eAXv0qwkO9zgffv9lQdSts_uRZCQI3Ro
  - eEHioWreeg7NLJkIUOmpLogMb0X0LMDP
  - edlFaCsuH_AXJsyV4q3dadoV-nh2lj7R
  - eeLHCIh4n_wnguIpYNqpD2Ge0l0usqSJ
  - esqIPICc7jDAken0xHwf9za4X21Cemt0
  - ftH32XHWwVFRwjfvWFXsWnmHM_gVtU12
  - gI9i7jV_rKL5TyY9CoEI9gysGu1W2HXj
  - gcyWXbvJVi0vjf4lLgIkR_0txpX8LAx9
  - gie8DH9dneyPGOyjs1un2ymDP0xWrWNH
  - hGET1IOjvnkKpvWAswZy_gOCE5QPnL83
  - hITui4New5dOgg5VxGLJBmaRtO2mCDgB
  - hPpm6lHwA2J3gmjDbvb1jxNJSqdDFvrX
  - hSdtCdi8DB_-2fMpHEFL6zsIpgdK5wVz
  - hkerfVO2smIEaljAGTK7hi_FxLt4mAmH
  - huRVT5BlKVdTYbUhQWrr2feodI612PZH
  - iBBlxz1g6bRadGEmm0d4kfTO5WRPQHKr
  - iiEoSDUL0o0Pg3eejq0ktCBdfbWFqBbN
  - ixZaSR2bFF5XplHrvc8r8vEMpkc8amOV
  - j5QOrc58fUSYWM7vbUAn0g4NIRwfOhBg
  - jby020CZB4zrQOSFa9G8HivhbhSYiJ2M
  - k7SM64BWbyyZThK-T5fr-8lJQcvGQ8Av
  - kLY1FsJeIOGv0X5bGcygEQer0x3CSOnf
  - kPijhP7oiAlbGOkJX4V0k759GIKvJ78y
  - kg00o09y82-Kgy_XKrS-FBySUm3VSGjW
  - khKoBTOWwXPmDIF0m2Snph5GX7BoJamR
  - lCuy7QUOM_Hpy3fm9sFL8j6SnbJd-FxI
  - lSxwFoA76iTlce0HDW85WtsKxvI7zeT2
  - lmkIchCJ1RIKsZvbb4HjCDl85B2nOicv
  - mE6bg3DCm-zMCm7_Nt8zOhETHz1XHoTE
  - myw7tebBIGbG5mQ7aAICzUtVSKlRQQhu
  - n0SjAV4pwqSUitFLGYmESXNC6guH6kQc
  - n3XL5R4agzVZ7DKs-j8dfEBkmqznu_Ck
  - ncZ-JURAz1ql5KxaJDQenRsPaLaHZ01b
  - ofHK3nQXlpAOUracjoR7TyUz00U6no0H
  - pDqaZ8h0HqfyQZIlyLByCEqDcQIOjvyT
  - prtHExKdxrEhGHKs3AaKgMkhCigMWx_u
  - qFDP9gJDz4MyXNxjl6mIEPFCUb8n1guU
  - qLpkgfo5MqE7jY9cPHlBvJfHncINeQxQ
  - qeLSfo0_ml9gey0TlIGHQFWNYB6vLixV
  - qn1eNtR0fm1ZJMypjAeec6yr-c7u2zJy
  - reigDTj3Eqg5IraZfRGRHJTCxvVqMtHh
  - rjYpw8awPfgy-JURa4FppspZoYloY-CH
  - sW4MEG73P0tPDuuXSUu6NAvx1KJSb10W
  - sgb9jS9iEBepAPRt-Ijrx83GuV2JPat-
  - si66tpk-az2gaLJaobIMXBpfh563i7Xg
  - tQDdQuDIPtVd-6P2MQSF-G75j-EP0pqv
  - tqQTCrVAo80-TggXDBfcrr4QOEiYFD-t
  - uNjwwJ2t4YyphdEcXW6aOstBFJ5m-2M2
  - uardbYKWhLLVyGoQpbp8_dpfIfbZSN1e
  - vWuqLpN3LO-EyUQ3MEvegQmXAbjkrnfK
  - vczXAwthxnadTYUS_TiR7IHiqEQrdSJx
  - wBPxyouyX9_6p1hGzIf8sYB9UPqpoBex
  - wHbdubn2UcxgoE5qVOtwQhJJw2AlZLzC
  - wXwTZnJHaWsMeYvf-hR0a3ZHrNXH3I0G
  - wweXnLBKNzbCxRHgq6frkOOGKxM4zJ4A
  - xFHjZynUy8kysoxYFZ26ie7xG_cjj8wU
  - xTGvmcjzDX2cgYhUThR3KSsZIM1s5fCR
  - xnKsFF3HurcEaPZ9og818sQMEzZlQDhV
  - y9FMchN_WFT0sKOUar9WcrUoiKHQwD4U
  - zY36WhUkV1AOl_aqxxBofB0_ash1nr7p
  - zis8Rpau1eqFncWiOgLfarbbFMzIBBjs
  - zy2XqqEo8pJc2qHyRvJwUrQkbCnDe3yd
  val_portion: 0.15
  val_sessions:
  - 0xCqEk5hjEvrygxu26MZkieSv45D_gaJ
  - 6DgHy7cTbWHs0HVSd9M6Mg2BqaqigjJr
  - 7PoccorPXoVcJawbvbCZizt4yBHF2SeB
  - C-g5n2_S5wUCaj75l2JdzeHyjxMBDxmv
  - CCG-oMqgJf90LzEhlqj0WkP3xN0dHlXk
  - KG6YYsHIQiosr82KhLO7g-CiXBP2g69u
  - KhNrNPHOOB9cKHWPWB-gJJlnH-r0b-FU
  - LLo6qRkbHPBDBjXs7_Gd2ao3vCXHnf-j
  - NFJk5-KAhky2rdjAC60WkmlvhKzaKcHZ
  - Nta3Pe6qqxaApoI2CuagFKvoj1mzwpCO
  - R-WZzQD8oC4jGO-iBhylUkbCU3DaxqeM
  - RbmdRLuI605cpRaLZzwOwDM9f1N5mfz1
  - TccwLbeRW-z_NPDDJsr1S3IC-iUzaJI3
  - Wa0yBTLPFCLYEmxwzfQ3gC6egLJOBkRf
  - We-WV-8Vm4iIQjrqprxcTUBltze15m5i
  - WyVSFIlpLuAjfwUfu_mA33YhggbZVzT_
  - Xk09VZarMEdAH4TlrzmwRmZZM-bk7XmS
  - YNo0wJ5J7GLXGsu-zkj-MXNqdvHJ-k_h
  - cBVSUvSNGsl6C4kHrsaG6RwL9u0L0Ln2
  - jLAxHSRZg9K-SFpF8_r16BSY79kEvbCJ
  - oCoFhQBFW4tQ-Y6MYaOlsdtwHd4t3XdU
  - qttyxduaRos5zTgIT4QHXy9Kr2uPEFYw
  - r7O3U6QanV_aqafpjva98r4ataD9BY50
  - vBzRkuHzUpRt-EhtMjPQODCEflzDjqio
  - wZ9KabBA03cxMpwWeYekeTGt502Ddp6h
  - xzZE8IX_uFMn4TDczrDP_jFNKQTYbvob
  - yGcmWEL64jMkK-ic2NWpFK4cpsCoJ8pN
  - yQ5Ij3w49RMUxxIai6ZVsvPHssZJ13FO
  - zTQeHx40GP76j6Nerv3kzTaR52dEfQ3j
